AppPath: D:\Wuthering Waves\Wuthering Waves Game\Wuthering Waves.exe
DungeonWeeklyBossLevel: '80'
RoleIndex: '1232312'
IsWei: true
TwoWei: 1
TargetBoss:
- 哀声鸷
FightTactics:
- a,e,q,s,a(0.5)
- q,e(0.7)
- a(1),e
- a(1.2),e
- a(1),q,0.2,a(0.8)
- a(1)
- a(1),e(2)
FightTacticsUlt:
- ''
TargetChallenge: ''
Automatic: true
