凝夜白霜:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
熔山裂谷:
  1COST: []
  3COST: []
  4COST: []
  PASS:
  - 暗鬃狼
彻空冥雷:
  1COST: []
  3COST: []
  4COST: []
  PASS:
  - 游鳞机枢
啸谷长风:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
浮星祛暗:
  1COST:
  - 攻击
  - 生命
  - 防御
  3COST: []
  4COST:
  - 暴击伤害
  PASS: []
沉日劫明:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
隐世回光:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
轻云出月:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
不绝余音:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
凌冽决断之心:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
此间永驻之光:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
幽夜隐匿之帷:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
高天共奏之曲:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
无惧浪涛之勇:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
流云逝尽之空:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
愿戴荣光之旅:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
奔狼燎原之焰:
  1COST: []
  3COST: []
  4COST: []
  PASS: []
